name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Set up Bun
              uses: oven-sh/setup-bun@v2


            - name: Install and Build              
              run: |
                    bun install --prod
                    bun run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                    github_token: ${{ github.token }}
                    publish_dir: ./dist
